# Generated by Django 3.2.9 on 2021-11-26 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kebab', '0002_auto_20211126_1859'),
    ]

    operations = [
        migrations.AddField(
            model_name='connection',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='menyu',
            name='image',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
